app/urls.py
from django.urls import path
from . import views



app_name = 'app'

urlpatterns = [
    path('', views.StoreNameView.as_view(), name='index'),
    # path('store_name', views.StoreNameView.as_view(), name='store_name'),
    path('date', views.DateView.as_view(), name='date'),
    path('detail', views.DetailView.as_view(), name='detail'),
    path('name', views.SlotNameView.as_view(), name='slot_name_list'),
    # path('all_display', views.AllDisplayView.as_view(), name='all_display'),
    # path('vue', views.vue, name='vue'),
] 

slotscrapingapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.

class PachiSlotStore(models.Model):
    class Meta:
          verbose_name_plural = '店舗'

    name = models.CharField(max_length=100, verbose_name='店舗名')
    memo = models.CharField(max_length=100, verbose_name='メモ', blank=True, null=True)

    def __str__(self):
          return self.name

class BusinessDay(models.Model):
    class Meta:
          verbose_name_plural = '営業日'
    date = models.DateField()
    store_name = models.ForeignKey(PachiSlotStore, on_delete=models.DO_NOTHING)
    total_pay = models.IntegerField(verbose_name='総差枚数', null=True)
    total_pay_pachinko = models.IntegerField(verbose_name='総出玉数', null=True)


#     def __str__(self):
#         return self.date

class SlotTitle(models.Model):
      class Meta:
          verbose_name_plural = '機種名'
      date = models.ForeignKey(BusinessDay, on_delete=models.DO_NOTHING, related_name="slot_title")
      name = models.CharField(max_length=100, verbose_name='機種名')
      numbers = models.IntegerField(verbose_name='台数', null=True)
      memo = models.CharField(max_length=100, verbose_name='メモ', blank=True, null=True)

      def __str__(self):
        return self.name

class Slot(models.Model):
    class Meta:
          verbose_name_plural = '台データ'
    name = models.CharField(max_length=100, verbose_name='機種名')
    date = models.ForeignKey(BusinessDay, on_delete=models.DO_NOTHING)
    number = models.IntegerField(verbose_name='台番号')
    bigbonus = models.IntegerField(verbose_name='BB')
    regularbonus = models.IntegerField(verbose_name='RB')
    count = models.IntegerField(verbose_name='総回転数')
    bbchance = models.CharField(max_length=10, verbose_name='BB確率', null=True)
    rbchance = models.CharField(max_length=10, verbose_name='RB確率', null=True)
    lastgames = models.IntegerField(verbose_name='宵越し', null=True)
    payout = models.IntegerField(verbose_name='差枚数')
    memo = models.CharField(max_length=100, verbose_name='メモ', blank=True, null=True)

    def __str__(self):
        return self.name

class Pachinko(models.Model):
      class Meta:
          verbose_name_plural = 'パチンコ'
      name = models.CharField(max_length=100, verbose_name='機種名')
      date = models.ForeignKey(BusinessDay, on_delete=models.DO_NOTHING)
      number = models.IntegerField(verbose_name='台番号')
      bonus = models.IntegerField(verbose_name='当たり')
      bbchance = models.CharField(max_length=10, verbose_name='当たり確率', null=True)
      count = models.IntegerField(verbose_name='総回転数')
      lastgames = models.IntegerField(verbose_name='宵越し', null=True)
      payout = models.IntegerField(verbose_name='差枚数')
      game_1k = models.FloatField(verbose_name='1kあたり目安', null=True)
      memo = models.CharField(max_length=100, verbose_name='メモ', blank=True, null=True)

      def __str__(self):
        return self.name

app/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from .models import *
import datetime
from django.db.models import Sum, Avg, aggregates



# class IndexView(TemplateView):
#     template_name = 'index.html'

class StoreNameView(ListView):
    model = PachiSlotStore
    template_name = 'index.html'
    context_object_name = "stores"

    def get_queryset(self):
        return PachiSlotStore.objects.all()

class DateView(ListView):
    model = BusinessDay
    template_name = 'date.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        store_name = self.request.GET.get('sn')
        dates = BusinessDay.objects.filter(
            store_name_id=store_name).distinct().order_by('-date')
        context['store_name'] = PachiSlotStore.objects.get(pk=store_name).name
        context['dates'] = dates

        return context

class SlotNameView(ListView):
    model = Slot
    
    template_name = 'slot_name_list.html'
    context_object_name = 'name_cnt'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        store_name = self.request.GET.get('sn')
        date = self.request.GET.get('date')
       
        nm = Slot.objects.filter(
            date=date,).distinct().values('name')
        name_cnt = {}
        avarage = []
        name_pay = []

        for n in nm:
            cnt = Slot.objects.filter(
                date=date, name=n['name']).values('name').count()
            name_cnt[n['name']] = cnt
        n_c = sorted(name_cnt.items(), key=lambda x: x[1], reverse=True)
        for n in n_c:

            ava = Slot.objects.filter(date=date, name=n[0]).aggregate(Avg('count'))
            ava = int(ava['count__avg'])
            avarage.append(ava)

            py = Slot.objects.filter(
                date=date, name=n[0]).aggregate(Sum('payout'))
            py = int(py['payout__sum'])
            name_pay.append(py)
        
        pachinko = Pachinko.objects.filter(date=date)

        context.update({
            'name_cnt': n_c,
            'store_name': store_name,
            'date': date,
            'avg': avarage,
            'py': name_pay,
            'pachinko': pachinko
        })
        return context

class DetailView(ListView):
    model = Slot
    template_name = 'detail.html'

    def queryset(self):
        store_name = self.request.GET.get('sn')
        day = self.request.GET.get('date')
        name = self.request.GET.get('name')
        dates = Slot.objects.filter(date=day, name=name)
        return dates

    def get_context_data(self):
        context = super().get_context_data()
        store_name = self.request.GET.get('sn')
        date = self.request.GET.get('date')
        name = self.request.GET.get('name')

        totalpay = Slot.objects.filter(date=date, name=name).aggregate(Sum('payout'))
        totalpay = totalpay['payout__sum']

        avgpay = Slot.objects.filter(date=date, name=name).aggregate(Avg('payout'))
        avgpay = (int)(avgpay['payout__avg'])

        avgcount = Slot.objects.filter(date=date, name=name).aggregate(Avg('count'))
        avgcount = (int)(avgcount['count__avg'])

        context['tp'] = totalpay
        context['ap'] = avgpay
        context['ac'] = avgcount
        return context

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <!-- linkタグでDataTableのcssファイルを読み込む -->
    <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/slotdata.css' %}">
   
    <title>パチスロデータアプリ</title>
</head>

<body>
    {% block content %}
    <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->
    {% endblock %}
    <!-- bootstrapのjavascrit読み込み-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

</body>
<!-- Vue読み込み -->
<script src="{% static 'assets/vuejs/vue.js' %}" type="text/javascript"></script>
{% block js %}

{% endblock %}


</html>

app/templates/date.html
<!-- 親テンプレートを読み込む-->
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="{% url 'app:index' %}">TOP</a></li>
            <li class="breadcrumb-item ">{{ store_name }}</li>
        </ol>
        <!--ページタイトル-->
        <div class="card mb-3">
            <div class="card-header">
                <h3><b>パチスロデータアプリ</b></h3>
            </div>
            <div class="card-body">
                <!-- テーブル表の定義 -->
                <div class="table-responsive">
                    <table width="100%" class="table table-striped table-bordered table-hover">
                        <!-- 表の列の定義-->
                        <thead>
                            <tr>
                                <th class="text-center">日付</th>
                                <th class="text-center">総差枚数</th>
                            </tr>
                        </thead>         　
                        <!-- ここまでが表の列の定義-->                     　
                        <!-- 表のデータ部分の表示-->
                        <tbody>
                            {% for item in dates %}
                            <tr class="odd gradeX text-center">
                                <td class="text-center" width="140">
                                    <a href="{% url 'app:slot_name_list' %}?sn={{ item.store_name }}&date={{ item.pk }}">
                                        {{ item.date }}, {{ item.date | date:"l"}}
                                    </a>
                                </td>
                                <td class="text-center" width="140">
                                    {{ item.total_pay }}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        　
                        <!-- ここまでが表のデータ部分の表示-->
                    </table>
                    <!-- ここまでがテーブル表の定義 -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/detail.html
<!-- 親テンプレートを読み込む-->
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <!-- パンくずリストの設定-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            </li>
            <li class="breadcrumb-item active">
                <a href="{% url 'app:slot_name_list' %}">
                    TOP
                </a>
            </li>
        </ol>
        <!--ページタイトル-->
        <div class="card mb-3">
            <div class="card-header">
                <h3><b>パチスロデータアプリ</b></h3>

            </div>
            <div class="card-body">
                <!-- テーブル表の定義 -->
                <div class="table-responsive">
                    <table width="100%" class="table table-striped table-bordered table-hover">
                        　
                        <!-- 表の列の定義-->

                        <thead>

                            <tr>


                                <th class="text-center">総差枚数</th>
                                <th class="text-center">平均回転数</th>
                                <th class="text-center">平均差枚数</th>
                                <!-- <th class="text-center">メモ</th> -->
                            </tr>
                        </thead>
                        　
                        <!-- ここまでが表の列の定義-->
                        　
                        <!-- 表のデータ部分の表示-->
                        <tbody>

                            <tr class="odd gradeX text-center">
                                <!-- <td class="text-center" width="100">{{ item.store_name }}</td>
                                <td class="text-center" width="100">{{ item.date }}</td> -->


                                <td class="text-center" width="140">{{ tp }}</td>
                                <td class="text-center" width="100">{{ ac }}</td>
                                <td class="text-center" width="140">{{ ap }}</td>
                                <!-- <td class="text-center" width="140">{{ item.memo }}</td> -->
                            </tr>


                        </tbody>
                        　
                        <!-- ここまでが表のデータ部分の表示-->
                    </table>
                    <br>
                    <hr>
                    <h3 class='text-center'><b>{% for item in object_list|slice:"0:1"%}

                            {{ item.name }}</b></h3>
                    {% endfor %}
                    <hr>
                    <br>
                    <!-- ここまでがテーブル表の定義 -->
                    <table width="100%" class="table table-striped table-bordered table-hover">
                        　
                        <!-- 表の列の定義-->

                        <thead>

                            <tr>

                                <!-- <th class="text-center">店舗名</th>
                                <th class="text-center">日付</th> -->

                                <th class="text-center">台番号</th>

                                <!-- <th class="text-center">機種名</th> -->
                                <th class="text-center">BB</th>
                                <th class="text-center">RB</th>
                                <th class="text-center">総回転数</th>
                                <th class="text-center">差枚数</th>
                                <th class="text-center">メモ</th>
                            </tr>
                        </thead>
                        　
                        <!-- ここまでが表の列の定義-->
                        　
                        <!-- 表のデータ部分の表示-->
                        <tbody>
                            {% for item in object_list %}
                            <tr class="odd gradeX text-center">
                                <!-- <td class="text-center" width="100">{{ item.store_name }}</td>
                                <td class="text-center" width="100">{{ item.date }}</td> -->

                                <td class="text-center" width="100">
                                    {{ item.number}}
                                </td>


                                <!-- <td class="text-center" width="100">{{ item.name }}</td> -->
                                <td class="text-truncate text-center" width="140">{{ item.bigbonus }}

                                </td>
                                <td class="text-center" width="140">{{ item.regularbonus }}</td>
                                <td class="text-center" width="100">{{ item.count }}</td>
                                <td class="text-center" width="140">{{ item.payout }}</td>
                                {% if item.memo == None %}
                                <td class="text-center" width="140"></td>
                                {% else %}
                                <td class="text-center" width="140">{{ item.memo }}</td>
                                {% endif %}
                            </tr>
                            {% endfor %}

                        </tbody>
                        　
                        <!-- ここまでが表のデータ部分の表示-->
                    </table>
                    <!-- ここまでがテーブル表の定義 -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'app:index' %}">TOP</a>
            </li>
        </ol>
        <div class="card mb-3">
            <div class="card-header">
                <h3><b>パチスロデータアプリ</b></h3>
            </div>
            <div class="card-body">
                <!-- テーブル表 -->
                <div class="table-responsive">
                    <table width="100%" class="table table-striped table-bordered table-hover">
                        <!-- 表の列の定義-->
                        <thead>
                            <tr>
                                <th class="text-center">店舗一覧</th>
                                <th class="text-center">メモ</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for store in stores %}
                            <tr class="odd gradeX text-center">
                                <td class="text-center"><a href="{% url 'app:date' %}?sn={{ store.pk }}">
                                        {{ store.name }}
                                    </a></td>
                                <td class="text-center" width=100>
                                    {% if store.memo == None %}

                                    {% else %}
                                    <a href="{% url 'app:index' %}?sn={{ item.store_name }}">
                                        {{ store.memo }}
                                    </a>
                                    {% endif %}
                                </td>
                                <!-- <td class="text-center" width="100">{{ item.name }}</td>
                                <td class="text-center" width="140">{{ item.number }}</td>
                                <td class="text-center" width="140">{{ item.date }}</td> -->
                            </tr>
                            {% endfor %}

                        </tbody>
                        　
                        <!-- ここまでが表のデータ部分の表示-->
                    </table>
                    <!-- ここまでがテーブル表の定義 -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/mohu.html
{% load static %}
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>slotdata</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>
    {% block main %}
    <div class="mx-auto" style="width: 200px;">


        <br><br><br>
        <div class="mx-auto" style="width: 200px;">

            <a href="{% url 'list:store_name' %}">
                <p class="text-center">入り口</p>

        </div>
        <div class="mx-auto" style="width: 200px;">

            <img class="d-block mx-auto" src="{% static 'assets/img/iriguchi.png' %}" width=100 height=100
                alt="Max-width 100">
            </a>
        </div>
    </div>
    {% endblock %}
</body>
</html>

app/templates/slot_name_list.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrappery">
    <div class="container-fluid">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            </li>
            <li class="breadcrumb-item active"><a href="{% url 'app:index' %}">TOP</a></li>
            <li class="breadcrumb-item active">
                {% for item in object_list|slice:"0:1"%}
                <a href="{% url 'app:index' %}">{{ item.store_name }}</a>
                {% endfor %}
            </li>
            <li class="breadcrumb-item active">
                {% for item in object_list|slice:"0:1"%}
                {{ item.date }}
                {% endfor %}
            </li>
            <li>機種名
            </li>
        </ol>
        <header>
            <h3><b>パチスロデータアプリ</b></h3>
        </header>
        <div class=" row m-1">
            <div class="col-8 p-0">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">機種名</th>
                            <th class="text-center">台</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for name, cnt in name_cnt %}
                        <tr class="odd gradeX text-center ">
                            <td class="text-center font-table">
                                <a href="{% url 'app:detail' %}?sn={{ store_name }}&date={{date}}&name={{name}}">
                                    {{ name|truncatechars:13}}
                                </a>
                            </td>
                            <td class="text-center font-table">
                                {{cnt}}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>　
                </table>
            </div>
            <div class="col-2 p-0">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">総差枚</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for payout in py %}
                        <tr class="odd gradeX text-center">
                            <td class="text-center font-table">
                                {{payout}}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>　
                </table>
            </div>
            <div class="col-2 p-0">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">平均G</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for avarage in avg %}
                        <tr class="odd gradeX text-center">
                            <td class="text-center font-table">
                                {{avarage}}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>　
                </table>
            </div>
            {% if pachinko %}
            <br>
            <div class="pachinko col-12">
                <h1 class="text-center">P海物語E (大海物語4SP)</h1>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr class="odd gradeX text-center">
                          
                            <td class="text-center font-table">
                                台番
                            </td>
                            <td class="text-center font-table">
                                １k目安
                            </td>
                            <td class="text-center font-table">
                                総回転
                            </td>

                            <td class="text-center font-table">
                                当たり
                            </td>
                            <td class="text-center font-table">
                                差枚数
                             </td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in pachinko %}
                        <tr class="odd gradeX text-center">
                          
                            <td class="text-center font-table">
                                {{p.number}}
                            </td>
                            <td class="text-center font-table">
                                {{p.game_1k}}
                            </td>
                            <td class="text-center font-table">
                                {{p.count}}
                            </td>
                            <td class="text-center font-table">
                                {{p.bonus}}
                            </td>
                            <td class="text-center font-table">
                                {{p.payout}}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>　

                </table>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}